# .streamlit/secrets.toml
AZURE_STORAGE_CONNECTION_STRING = "DefaultEndpointsProtocol=https;AccountName=sethappstorage;AccountKey=h4AKTBNIheZyP6uuqBzeyNidFN8WYPYgOrzaMkWkaCBFIhLgJH/8L+8mASOzX6G29GaCZ1BYatcq+AStkZnL6g==;EndpointSuffix=core.windows.net"
AZURE_STORAGE_CONTAINER_NAME = "bowling-assistant"
GEMINI_API_KEY = "AIzaSyAdWxIZ9YKxIoQoTDKIlyBKOqxlmS6Ks38"